name: Build and publish ubuntu22.04 based Docker images

on:
  workflow_dispatch:
  schedule:
    - cron: "22 04 1,15 * *"

jobs:
  xrdp-ubuntu22_04:
    uses: ./.github/workflows/xrdp-ubuntu22.04.yml
    secrets: inherit

  xrdp-ubuntu22_04_pulseaudio:
    needs: [xrdp-ubuntu22_04]
    uses: ./.github/workflows/xrdp-ubuntu22.04_pulseaudio.yml
    secrets: inherit

  xrdp-ubuntu22_04_slim:
    uses: ./.github/workflows/xrdp-ubuntu22.04_slim.yml
    secrets: inherit

  vnc-ubuntu22_04:
    uses: ./.github/workflows/vnc-ubuntu22.04.yml
    secrets: inherit

  vnc-ubuntu22_04_slim:
    uses: ./.github/workflows/vnc-ubuntu22.04_slim.yml
    secrets: inherit
